addons:
  hosts:
    - rabbit.local
    - database.local
    - localhost

language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  allow_failures:
    - php: 7.1

before_install:
  - phpenv config-add travis/z_php.ini
  - bash travis/install-apcu-pecl.sh

before_script:
  - sudo apt-get install librabbitmq-dev
  - sudo apt-get install php-amqp
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - SYMFONY_PHPUNIT_VERSION=6.5 SYMFONY_DEPRECATIONS_HELPER=weak_vendors bin/simple-phpunit --debug --coverage-clover ./test/clover.xml

after_script:
  - composer require php-coveralls/php-coveralls:^2.0
  - php ./vendor/php-coveralls/php-coveralls/bin/php-coveralls -v

services:
  - rabbitmq