addons:
  hosts:
    - rabbit.local
    - database.local
    - localhost

language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

matrix:
  allow_failures:
    - php: 7.2

before_install:
  - phpenv config-add travis/z_php.ini
  - bash travis/install-apcu-pecl.sh

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak bin/phpunit --debug

services:
  - rabbitmq