version: '3'
services:
  redis:
    image: redis:3-alpine
  php:
    build: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv:rw
    depends_on:
      - redis
      - rabbit.local
    environment:
      SYMFONY_PHPUNIT_VERSION: 7.4
      SYMFONY_DEPRECATIONS_HELPER: weak_vendors

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/:/srv/web/:ro
    ports:
      - "8080:80"

  rabbit.local:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
