services:
    smartbox.clients.rest.remote_system_api:
        class: GuzzleHttp\Client
        arguments: [{timeout: 0, allow_redirects: false, verify: false}]
        lazy: true
        tags:
          - { name: mockable.rest_client, mockLocation: "%external_system_responses_cache_dir%/remoteSystemApi" }

smartbox_integration_framework:
    mappings:
        pingToRemoteApi:
            message: obj.getMessage()
            time: obj.getTimestamp()

        pingCallbackToOriginatingSystem:
            message: obj.getMessage()
            originalTime: obj.getTimestamp()

    producers:
        remote_system_api:
            class: SmartboxSkeletonBundle\Producers\RemoteSystemApiProducer
            description: producers to connection to a remote api
            calls:
              - [setName, ['remote_system_api'] ]
              - [setHttpClient, ['@smartbox.clients.rest.remote_system_api'] ]
              - [setValidator, ['@validator']]
              - [setHydrator,['@smartcore.hydrator.group_version'] ]

            options:
                encoding: json
                base_uri: '%remote_system_api.base.uri%'
                authentication: 'none'
                username: '%remote_system_api.username%'
                password: '%remote_system_api.password%'


            methods:
                sendPingMessage:
                    description: 'Send ping to a remote api'
                    steps:
                      - define:
                          PingMessage: "eval: body"
                      - request:
                          name: sendPingMessage
                          http_method: POST
                          uri: /smartesb-skeleton/web/remote/pong
                          body: "eval: mapper.map(PingMessage, 'pingToRemoteApi')"
                          validations:
                              - rule: "eval: responses['sendPingMessage']['statusCode'] == 200"
                                message: "eval: 'Enexpected response from Web Api: ' ~ responses['sendPingMessage']['statusCode']"
                                recoverable: true
                                display_message: true
                    response:
                        body: "eval: responses['sendPingMessage']['body']"

                logContent:
                    description: 'Log some data'
                    steps:
                      - define:
                          Message: "eval: body"
                      - request:
                          name: logContent
                          http_method: POST
                          uri: /smartesb-skeleton/web/remote/logContent
                          body: "eval: Message"
                          validations:
                              - rule: "eval: responses['logContent']['statusCode'] == 200"
                                message: "eval: 'Enexpected response from Web Api: ' ~ responses['logContent']['statusCode']"
                                recoverable: true
                                display_message: true
                    response:
                        body: "eval: responses['logContent']['body']"

                sendPingCallback:
                    description: 'Send ping to a remote api'
                    steps:
                      - define:
                          PingCallback: "eval: body"
                      - request:
                          name: sendPingCallback
                          http_method: POST
                          uri: /smartesb-skeleton/web/pingCallback
                          body: "eval: mapper.map(PingCallback, 'pingCallbackToOriginatingSystem')"
                    response:
                        body: "eval: responses['sendPingCallback']['body']"
