imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SmartboxSkeletonBundle/Resources/config/services.yml" }
    - { resource: "@SmartboxSkeletonRemoteDemoBundle/Resources/config/services.yml" }
    - { resource: producers/remote_system_api.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    flows_path: "%kernel.root_dir%/config/flows"
    frozen_flows_path: "%kernel.root_dir%/config/frozen_flows"
    fixtures_path: "%kernel.root_dir%/Resources/Fixtures"

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

monolog:
    channels: [tracking]
    handlers:
        syslog:
            type: syslog
            level: debug
            formatter: smartcore.monolog.formatter.json
        syslog_tracking:
            type: syslog
            level: debug
            formatter: smartcore.monolog.formatter.json
            channels: [tracking]

#Smartbox core configuration
smartbox_core:
    cache_drivers:
        null:
            service: ~
#    fixtures_path: "%kernel.root_dir%/JsonFixtures"
#    entities_namespaces:
#        - 'Smartbox\Integration\Framework\Entity'

smartbox_integration_framework:
    defer_events_to_uri: "queue://events"
    queue_drivers:
        rabbitmq:
            type: RabbitMQ
            description: RabbitMQ queue driver
            host: "%rabbitmq.hostname%"
            username: "%rabbitmq.username%"
            password: "%rabbitmq.password%"
            format: json
            vhost: '%rabbitmq.vhost%'
            timeout: '%rabbitmq.timeout%'
        async_rabbitmq:
            type: RabbitMQ
            description: RabbitMQ queue driver
            host: "%rabbitmq.hostname%"
            username: "%rabbitmq.username%"
            password: "%rabbitmq.password%"
            sync: false
            format: json
            vhost: '%rabbitmq.vhost%'
            timeout: '%rabbitmq.timeout%'

    nosql_drivers: ~

    default_queue_driver: '%default.queues.driver%'
    default_nosql_driver: ~

    message_handlers:
        sync:
            description: Message hanlder to handle messages comming from the API
            retries_max: 5
            retry_delay: 0
            failed_uri: queue://main/sync/failed
            retry_uri: queue://main/sync/retry
            throw_exceptions: true
            defer_new_exchanges: true

        async:
            description: Message hanlder to handle messages comming from a queue
            retries_max: 5
            retry_delay: 0
            failed_uri: queue://main/async/failed
            retry_uri: original
            throw_exceptions: false
            defer_new_exchanges: true
#            throttle_delay: 1
#            throttle_delay_factor: 1
#            throttle_strategy: fixed
#            throttle_uri: queue://main/throttlerAsync

    flows_version: 0
    queues_default_persistence: false
    enable_logging: true
    errors_log_level: debug
    events_log_level: info
    #queues_default_ttl
    #defer_events_to_uri
    latest_flows_version: 0
    enable_events_deferring: true



smartbox_integration_camel_config:
    flows_directories:
      - "%flows_path%"
    frozen_flows_directory: "%frozen_flows_path%"
