# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
     smartesb_skeleton_dummy_service:
        class: SmartboxSkeletonBundle\Services\DummyService
        arguments: ["@logger","@kernel"]
        tags:
            - { name: monolog.logger, channel: skeleton }

     smartesb_skeleton_request_handler:
        class: SmartboxSkeletonBundle\Services\RequestHandlerService
        arguments: ["@kernel"]
        tags:
            - { name: monolog.logger, channel: skeleton }
