smartbox_skeleton_homepage:
    path:     /
    defaults: { _controller: SmartboxSkeletonBundle:Default:index }

smartbox_skeleton_api:
    path:     /api/{methodName}
    defaults: { _controller: SmartboxSkeletonBundle:Api:api,"methodName" : "" }

smartbox_skeleton_callback:
    path:     /pingCallback
    defaults: { _controller: SmartboxSkeletonBundle:Api:pingCallback }