theme: jekyll-theme-minimal

collections_dir: pages
collections:
  introduction:
    output: true
  samples:
    output: true
  bundles:
    output: true
  other:
    output: true
  camel:
    output: true

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
baseurl: '/smartesb-skeleton'

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM #Github Flavored Markdown
  hard_wrap: false
  syntax_highlighter: rouge

host: 0.0.0.0
repository: smartboxgroup/smartesb-skeleton