theme: jekyll-theme-minimal

collections_dir: pages
collections:
  introduction:
    output: true
  samples:
    output: true
  bundles:
    output: true

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
